<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function htmx_preprocess_html(&$variables) {
  $variables['#attached']['library'][] = 'htmx/htmx';
}

/**
 * Implements hook_theme().
 */
function htmx_theme($existing, $type, $theme, $path) {
  return [
    'htmx_demo' => [
      'variables' => [
        'button_text' => NULL,
      ],
      'template' => 'htmx-demo',
    ],
    'htmx_demo_users' => [
      'variables' => [
        'users' => NULL,
      ],
      'template' => 'htmx-demo-users',
    ],
  ];
}
